### ISSUE TITLE
/api/v3/exchangeInfo is throwing error

### ISSUE THREAD

**Issue by martin-studna** [JKorf/Binance.Net#1028]
If I call `client.Spot.System.GetExchangeInfoAsync()` I will get the following error:

```
Deserialize Unknown Exception: ArgumentNullException - Value cannot be null. (Parameter ''item'')
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at CryptoExchange.Net.BaseClient.DeserializeAsync[T](Stream stream, JsonSerializer serializer, Nullable`1 requestId, Nullable`1 elapsedMilliseconds)
', Data: '[Data only available in Debug LogLevel]'}
```

Does it have something to do with the new introduced parameter "allowTraillingStop" as it is mentioned on binance api changelog from 28.2.2022?

**Comment by JKorf** [comment]
Are  you running the latest version of Binance.Net?

**Comment by martin-studna** [comment]
I have version 7.2.7

**Comment by JKorf** [comment]
A new enum value has been added, which causes this error. This has been resolved in the latest version. So if you can update, that would be the way to go. This is a bit of a task as there have been some breaking changes.
Alternatively you can clone the 7.2.7 version and fix the issue yourself, see #1007

**Comment by HypsyNZ** [comment]
> Alternatively you can clone the 7.2.7 version and fix the issue yourself, see #1007

You should add a tag to your commit with the version number when you update versions to make this easier.

They will also show up under "tags" on github

**Comment by JKorf** [comment]
That's a good idea, I'll look into this

**Comment by JKorf** [comment]
I've added some tags for previous versions and added automatic tagging for new releases
