### ISSUE TITLE
Moving Blazor.ClientSide example to .NET 6: Operation is not supported on this platform

### ISSUE THREAD

**Issue by gl9209** [JKorf/Binance.Net#1051]
Moving Blazor.ClientSide example (https://github.com/JKorf/Binance.Net/tree/master/Examples/Blazor.ClientSide) to .NET 6: Operation is not supported on this platform

To reproduce: create new Blazor WASM project

From original:

Copy Index.razor

Copy BinanceClient.SetDefaultOptions from Program.cs

Copy dependency injection code from Program.cs

Reference Blazor.DataProvider

result: Get24HPrices() works fine, then:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Operation is not supported on this platform.
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocketOptions.set_Cookies(CookieContainer value)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.CreateSocket()
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient..ctor(Log log, String url, IDictionary`2 cookies, IDictionary`2 headers)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient..ctor(Log log, String url)
   at CryptoExchange.Net.Sockets.WebsocketFactory.CreateWebsocket(Log log, String url)
   at CryptoExchange.Net.BaseSocketClient.CreateSocket(String address)
   at CryptoExchange.Net.BaseSocketClient.GetSocketConnection(SocketApiClient apiClient, String address, Boolean authenticated)
   at CryptoExchange.Net.BaseSocketClient.<SubscribeAsync>d__36`1[[Binance.Net.Objects.Models.BinanceCombinedStream`1[[System.Collections.Generic.IEnumerable`1[[Binance.Net.Objects.Models.Spot.Socket.BinanceStreamTick, Binance.Net, Version=8.0.3.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Binance.Net, Version=8.0.3.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Binance.Net.Clients.SpotApi.BinanceSocketClientSpotStreams.SubscribeToAllTickerUpdatesAsync(Action`1 onMessage, CancellationToken ct)
   at WasBin.Pages.Index.OnInitializedAsync() in C:\Documents\Repos\2020B\WasBin\WasBin\Pages\Index.razor:line 27
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

[binance.net trace.txt](https://github.com/JKorf/Binance.Net/files/8457559/binance.net.trace.txt)

**Comment by HypsyNZ** [comment]
Are you using Windows 7? 

If so, Please upgrade to at least Windows 10, You can download a secure version of Windows 10 [Here](https://github.com/HypsyNZ/ISOKIT)

**Comment by gl9209** [comment]
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1620
Windows Feature Experience Pack 120.2212.4170.0

**Comment by HypsyNZ** [comment]
[PlatformNotSupportedException](https://docs.microsoft.com/en-us/dotnet/api/system.platformnotsupportedexception?view=net-6.0)

> The exception that is thrown when a feature does not run on a particular platform.

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
```

It looks like this isn't available in .NET 6, or something that it is calling internally.

**Comment by HypsyNZ** [comment]
Is there any reason why you "upgraded" to .NET 6?

**Comment by gl9209** [comment]
.NET 6 WebAssembly is a subset of .NET 6, that would explain the missing feature. But the feature is available in netstandard2.1, which the fully working example is in. I'm surprised that .NET 6 WebAssembly is missing a feature that is present in netstandard2.1 WebAssembly.

It's possible that I've done something wrong, I would really appreciate someone trying to make the example work in .NET 6. It should only take a couple of minutes.

**Comment by HypsyNZ** [comment]
Did you get this working?

**Comment by gl9209** [comment]
No. Have you tried it?

**Comment by Andrei088** [comment]
I encountered the same issue for Blazor Client, but haven't found a solution yet.
Has anyone found a way to get rid of this error?

**Comment by JKorf** [comment]
In that latest CryptoExchange.Net version 5.2.4 I've added handling for the exception thrown when setting cookies (and other options) on the websocket. I managed to get the price stream working with that, but I'm not sure if everything now works correctly.

Have a go with it (you'll have to manually install CryptoExchange.Net version 5.2.4 as the implementations still use an older version) and let me know if you have any other issues. Or if it works correctly.

**Comment by Andrei088** [comment]
@JKorf I've just made a quick test and it seems the exception handling did the trick. (tested the provided example with .NET 6 Blazor WebAssembly). Not being able to set options for the WebSocket isn't great, but this is probably a limitation by WebAssembly/browser's security at the moment.
If anything else pops up regarding this issue, I will post it.
Thank you.
