### ISSUE TITLE
Blazor WebAssembly Support

### ISSUE THREAD

**Issue by Kiryuumaru** [JKorf/Binance.Net#1128]
**Describe the bug**
I am trying to run my project with Blazor WebAssembly but it seems something in HttpClient socket is not supported.

**To Reproduce**
Make a Blazor WebAssembly project in vs 2022 and try to SubscribeToAllMiniTickerUpdatesAsync.

**Expected behavior**
The live Ticker updates from the socket.

**Debug logging**
In my chrome console:
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Operation is not supported on this platform.
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.BrowserHttpHandler.set_Proxy(IWebProxy value)
   at System.Net.Http.HttpClientHandler.set_Proxy(IWebProxy value)
   at CryptoExchange.Net.Requests.RequestFactory.Configure(TimeSpan requestTimeout, ApiProxy proxy, HttpClient client)
   at CryptoExchange.Net.BaseRestClient..ctor(String name, BaseRestClientOptions options)
   at Binance.Net.Clients.BinanceClient..ctor(BinanceClientOptions options) . . . .

**Comment by JKorf** [comment]
Hi, this seems to be caused by some socket options not being available when running from WebAssembly. I've added some checks in the latest CryptoExchange.Net library which you can test. (Binance.Net doesn't have a reference to that version yet, but you can install the latest CryptoExchange.Net manually into you project).
My quick tests seems to show that socket connections work not from WebAssembly, but let me know if you have any issues.
