### ISSUE TITLE
'Request timed out' Error in last version

### ISSUE THREAD

**Issue by SergeevGregory** [JKorf/Binance.Net#1135]
Hello, JKorf!
During use rest ap (spot and futures) I have '[XXX] Request timed out' very often (for example while canceling order) in last version. When I used previous version of binance.net (8.0.9) (and cryptoexchange 5.1.6) this problem didn't appear. Hope you will help this issue.

P.S. I use binance.net on Ubuntu 22.04 + dotnet 6.0

Greg

**Comment by SergeevGregory** [comment]
```
I: 8/10/2022 3:58:17 PM Binance    | [340] Creating request for https://api.binance.com/api/v3/order
T: 8/10/2022 3:58:17 PM Binance    | [340] Sending POST signed request to https://api.binance.com/api/v3/order with request body 'newClientOrderId=TAILS_TEST_BTC_OLL_1660136297832&price=0.07435&quantity=0.00140000&recvWindow=5000&side=BUY&signature=C9048CE50D3D9229F1A2D240B7716B43CF62A6B369E82462DEA53A9B8438898E&symbol=PAXGBTC&timeInForce=GTC&timestamp=1660136297853&type=LIMIT' with headers Accept=[application/json], X-MBX-APIKEY=[XIKG1XyloeReuN55xOFOoEUwgq4lS4UnfSKFzm1UJwBWePOwzICXBwzh4TIZN7KU]
D: 8/10/2022 3:58:18 PM Binance    | [340] Response received in 565ms: {"symbol":"PAXGBTC","orderId":80989721,"orderListId":-1,"clientOrderId":"TAILS_TEST_BTC_OLL_1660136297832","transactTime":1660136298293,"price":"0.07435000","origQty":"0.00140000","executedQty":"0.00000000","cummulativeQuoteQty":"0.00000000","status":"NEW","timeInForce":"GTC","type":"LIMIT","side":"BUY","fills":[]}
I: 8/10/2022 3:59:55 PM Binance    | [341] Creating request for https://api.binance.com/api/v3/order
T: 8/10/2022 3:59:55 PM Binance    | [341] Sending DELETE signed request to https://api.binance.com/api/v3/order with request body 'orderId=80989721&recvWindow=5000&signature=9502D7AFCB32E48524D8092B9AFCF4BD924AB6480B6DC02456FB632D1D6E80F4&symbol=PAXGBTC&timestamp=1660136395415' with headers Accept=[application/json], X-MBX-APIKEY=[XIKG1XyloeReuN55xOFOoEUwgq4lS4UnfSKFzm1UJwBWePOwzICXBwzh4TIZN7KU]
I: 8/10/2022 4:03:10 PM Binance    | [343] Creating request for https://api.binance.com/api/v3/time
T: 8/10/2022 4:03:10 PM Binance    | [343] Sending GET request to https://api.binance.com/api/v3/time with headers Accept=[application/json], X-MBX-APIKEY=[XIKG1XyloeReuN55xOFOoEUwgq4lS4UnfSKFzm1UJwBWePOwzICXBwzh4TIZN7KU]
I: 8/10/2022 4:03:10 PM Binance    | [342] Creating request for https://api.binance.com/api/v3/account
T: 8/10/2022 4:03:10 PM Binance    | [342] Sending GET signed request to https://api.binance.com/api/v3/account?recvWindow=5000&signature=3D4CD7E76BE0932F8B47E2AF501451FDA60E5C2A715F7B83212C7E2162CBE266&timestamp=1660136590533 with headers Accept=[application/json], X-MBX-APIKEY=[XIKG1XyloeReuN55xOFOoEUwgq4lS4UnfSKFzm1UJwBWePOwzICXBwzh4TIZN7KU]
I: 8/10/2022 4:13:29 PM Binance    | [344] Creating request for https://api.binance.com/api/v3/account
T: 8/10/2022 4:13:29 PM Binance    | [344] Sending GET signed request to https://api.binance.com/api/v3/account?recvWindow=5000&signature=3E40AAF21D72F22983FBF80D39BB00A50DE75B4A967C94232F4228A4E09FB93A&timestamp=1660137209826 with headers Accept=[application/json], X-MBX-APIKEY=[XIKG1XyloeReuN55xOFOoEUwgq4lS4UnfSKFzm1UJwBWePOwzICXBwzh4TIZN7KU]
W: 8/10/2022 4:15:13 PM Binance    | [344] Request timed out: TaskCanceledException - The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at CryptoExchange.Net.Requests.Request.GetResponseAsync(CancellationToken cancellationToken)
   at CryptoExchange.Net.BaseRestClient.GetResponseAsync[T](BaseApiClient apiClient, IRequest request, JsonSerializer deserializer, CancellationToken cancellationToken, Boolean expectedEmptyResponse)
  TimeoutException - A task was canceled.
  
    TaskCanceledException - A task was canceled.
       at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

I: 8/10/2022 4:23:41 PM Binance    | [345] Creating request for https://api.binance.com/api/v3/account
T: 8/10/2022 4:23:41 PM Binance    | [345] Sending GET signed request to https://api.binance.com/api/v3/account?recvWindow=5000&signature=CF558CEAEF47C85BB6C3B231C0147F988EF7D79BBE248A281B17F1A47433D556&timestamp=1660137821308 with headers Accept=[application/json], X-MBX-APIKEY=[XIKG1XyloeReuN55xOFOoEUwgq4lS4UnfSKFzm1UJwBWePOwzICXBwzh4TIZN7KU]
W: 8/10/2022 4:25:22 PM Binance    | [345] Request timed out: TaskCanceledException - The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at CryptoExchange.Net.Requests.Request.GetResponseAsync(CancellationToken cancellationToken)
   at CryptoExchange.Net.BaseRestClient.GetResponseAsync[T](BaseApiClient apiClient, IRequest request, JsonSerializer deserializer, CancellationToken cancellationToken, Boolean expectedEmptyResponse)
  TimeoutException - A task was canceled.
  
    TaskCanceledException - A task was canceled.
       at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
 
```

After 3:58:17 all requests fails without response...

**Comment by SergeevGregory** [comment]
```
I: 8/10/2022 3:58:17 PM Binance    | [340] Creating request for https://api.binance.com/api/v3/order
T: 8/10/2022 3:58:17 PM Binance    | [340] Sending POST signed request to https://api.binance.com/api/v3/order with request body '...' with headers Accept=[application/json], X-MBX-APIKEY=[...]
D: 8/10/2022 3:58:18 PM Binance    | [340] Response received in 565ms: {....}
I: 8/10/2022 3:59:55 PM Binance    | [341] Creating request for https://api.binance.com/api/v3/order
T: 8/10/2022 3:59:55 PM Binance    | [341] Sending DELETE signed request to https://api.binance.com/api/v3/order with request body '...' with headers Accept=[application/json], X-MBX-APIKEY=[...]
I: 8/10/2022 4:03:10 PM Binance    | [343] Creating request for https://api.binance.com/api/v3/time
T: 8/10/2022 4:03:10 PM Binance    | [343] Sending GET request to https://api.binance.com/api/v3/time with headers Accept=[application/json], X-MBX-APIKEY=[...]
I: 8/10/2022 4:03:10 PM Binance    | [342] Creating request for https://api.binance.com/api/v3/account
T: 8/10/2022 4:03:10 PM Binance    | [342] Sending GET signed request to https://api.binance.com/api/v3/account?recvWindow=5000... with headers Accept=[application/json], X-MBX-APIKEY=[...]
I: 8/10/2022 4:13:29 PM Binance    | [344] Creating request for https://api.binance.com/api/v3/account
T: 8/10/2022 4:13:29 PM Binance    | [344] Sending GET signed request to https://api.binance.com/api/v3/account?recvWindow=5000... with headers Accept=[application/json], X-MBX-APIKEY=[...]
W: 8/10/2022 4:15:13 PM Binance    | [344] Request timed out: TaskCanceledException - The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at CryptoExchange.Net.Requests.Request.GetResponseAsync(CancellationToken cancellationToken)
   at CryptoExchange.Net.BaseRestClient.GetResponseAsync[T](BaseApiClient apiClient, IRequest request, JsonSerializer deserializer, CancellationToken cancellationToken, Boolean expectedEmptyResponse)
  TimeoutException - A task was canceled.
  
    TaskCanceledException - A task was canceled.
       at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

I: 8/10/2022 4:23:41 PM Binance    | [345] Creating request for https://api.binance.com/api/v3/account
T: 8/10/2022 4:23:41 PM Binance    | [345] Sending GET signed request to https://api.binance.com/api/v3/account?recvWindow=5000&signature=CF558CEAEF47C85BB6C3B231C0147F988EF7D79BBE248A281B17F1A47433D556&timestamp=1660137821308 with headers Accept=[application/json], X-MBX-APIKEY=[XIKG1XyloeReuN55xOFOoEUwgq4lS4UnfSKFzm1UJwBWePOwzICXBwzh4TIZN7KU]
W: 8/10/2022 4:25:22 PM Binance    | [345] Request timed out: TaskCanceledException - The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at CryptoExchange.Net.Requests.Request.GetResponseAsync(CancellationToken cancellationToken)
   at CryptoExchange.Net.BaseRestClient.GetResponseAsync[T](BaseApiClient apiClient, IRequest request, JsonSerializer deserializer, CancellationToken cancellationToken, Boolean expectedEmptyResponse)
  TimeoutException - A task was canceled.
  
    TaskCanceledException - A task was canceled.
       at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
 
```
There no response after CancelOrder... Any ideas?

**Comment by ertan2002** [comment]
I have the same problem. I am using parallel for each for the GetKlinesAsync method for 3-5 minutes intervals. 
As I see, you closed this topic @SergeevGregory  Did you find a solution?
