### ISSUE TITLE
GetLendingAccountAsync Deprecated

### ISSUE THREAD

**Issue by Giampli** [JKorf/Binance.Net#1341]
**Describe the bug**
Trying to get from GeneralApi.Savings.GetLendingAccountAsync() it get back an error saying that it has been deprecated

**To Reproduce**
Simply call the GeneralApi.Savings.GetLendingAccountAsync()

**Expected behavior**
To get position from Binance Earn

**Debug logging**
 System.Exception: This endpoint has been deprecated, please remove as soon as possible.
         at Importer.BinanceImport.GetLendingPositions() in path_to_invocation_class:line 54
         at Importer.Worker.<BinanceRefreshTimer_Elapsed>b__5_2() in path_to_invocation_class:line 56

**Comment by JozefGula** [comment]
@JKorf I know you certainly have a lot, but would it be possible to look at it?

I have the same problem when calling "GetFlexibleProductPositionAsync"

**Comment by JKorf** [comment]
Yeah I'll have a look soon, Finishing up some other things

**Comment by JKorf** [comment]
I've added the SimpleEarn endpoints under the GeneralApi in the latest version, more missing endpoints will following in coming weeks.
