### ISSUE TITLE
BinanceSocketClient - Can't connect to the server

### ISSUE THREAD

**Issue by AlgoExecutor** [JKorf/Binance.Net#1361]
Looks like there is a problem with `BinanceClientSocket` class. When I call the endpoint GetServerTime I get: **Can't connect to the server**
Binance.Net Version **9.7.1**

You can easily reproduce it with the following code:
```
 var socketClient = new BinanceSocketClient();
 var time = socketClient.SpotApi.ExchangeData.GetServerTimeAsync().Result;
 if(!time.Success)
     Console.WriteLine("Error: " + time.Error);
```

Debug Logging:
fail: Binance[1001]
      **[Sckt 1] connection failed: The server returned status code '403' when status code '101' was expected.**
      System.Net.WebSockets.WebSocketException (203): The server returned status code '403' when status code '101' was expected.
         at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
         at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
         at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectInternalAsync()

**Comment by AlgoExecutor** [comment]
Ups, maybe i got blocked somehow.
