### ISSUE TITLE
Can't serialize BinanceSymbol

### ISSUE THREAD

**Issue by HarshDaga** [JKorf/Binance.Net#201]
Newtonsoft.Json fails to serialize a `BinanceSymbol` object with the error:
"Unable to cast object of type 'Binance.Net.Objects.OrderType[]' to type 'Binance.Net.Objects.OrderType'."

**Comment by JKorf** [comment]
Can you provide some more details on the data you receive by setting LogVerbosity to Debug in the client options and paste the received data?

**Comment by HarshDaga** [comment]
"Unable to cast object of type 'Binance.Net.Objects.OrderType[]' to type 'Binance.Net.Objects.OrderType'."

Stacktrace:
  at Binance.Net.Converters.OrderTypeConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, Formatting formatting, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting)

**Comment by HarshDaga** [comment]
Changing the attribute on `OrderTypes` from `[JsonConverter(typeof(OrderTypeConverter))]` to `[ItemConverterType=typeof(OrderTypeConverter))]` should fix it?
I haven't tested it yet.

**Comment by JKorf** [comment]
This seems to be when serializing the data instead of deserializing it, are you trying to write the object to a file or something like that?

**Comment by HarshDaga** [comment]
Yes, I am trying to serialize it to json.
I haven't tested deserializing it since I couldn't get serializing to work in the first place.

**Comment by JKorf** [comment]
I see, fixed it. Instead of using the ItemConverterType attribute I parsing the array manually when reading, but there was no support for this when writing. It's now using `ItemConverterType` properly. 
This will be included in next release, however I feel like this is to small to make a new version for.
