### ISSUE TITLE
Get tickers socket exception

### ISSUE THREAD

**Issue by Hulkstance** [JKorf/Binance.Net#403]
Is that exception a normal behavior for the ticker's socket? It is only happening with this particular subscription. Shortened the received data below, so I can submit the issue. By the way, I'm using Binance.Net v5.1.14 NuGet package.

```
2020/08/27 16:01:20:309 | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: Set, BaseAddress: https://api.binance.com, Proxy: -, RateLimiters: 0, RateLimitBehaviour: Wait, RequestTimeout: 00:00:30
2020/08/27 16:01:20:326 | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: Set, BaseAddress: wss://stream.binance.com:9443/ws/, Proxy: -, AutoReconnect: True, ReconnectInterval: 00:00:30, SocketResponseTimeout: 00:00:10, SocketSubscriptionsCombineTarget: 
2020/08/27 16:01:20:340 | Debug | Creating request for https://api.binance.com/api/v3/ticker/24hr
2020/08/27 16:01:20:356 | Debug | Sending GET request to https://api.binance.com/api/v3/ticker/24hr 
2020/08/27 16:01:21:921 | Debug | Data received: ...
2020/08/27 16:01:22:264 | Debug | Created new socket for wss://stream.binance.com:9443/ws/!ticker@arr
2020/08/27 16:01:22:281 | Debug | Socket 1 connecting
2020/08/27 16:01:23:864 | Debug | Socket 1 connected
2020/08/27 16:01:33:349 | Debug | Socket 1 received data: ...
2020/08/27 16:01:46:073 | Debug | Socket 1 received data: ...
2020/08/27 16:01:56:162 | Debug | Socket 1 received data: ...
2020/08/27 16:02:04:310 | Info | Socket 1 error: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.ReadAsync()
2020/08/27 16:02:04:313 | Info | Socket 1 Connection lost, will try to reconnect after 00:00:30
The thread 0x1280 has exited with code 0 (0x0).
2020/08/27 16:02:34:330 | Debug | Socket 1 resetting
2020/08/27 16:02:34:336 | Debug | Socket 1 connecting
2020/08/27 16:02:35:563 | Debug | Socket 1 connected
2020/08/27 16:02:35:566 | Info | Socket 1 reconnected after 00:00:31.2534785
2020/08/27 16:02:35:570 | Debug | All subscription successfully resubscribed on reconnected socket.
2020/08/27 16:02:45:246 | Debug | Socket 1 received data: ...
The thread 0x4e9c has exited with code 0 (0x0).
2020/08/27 16:03:00:606 | Debug | Socket 1 received data: ...
```

```csharp
public void GetTickers()
{
	var pricesList = Client.Get24HPricesList();

	while (!pricesList.Success)
	{
		var weight = BinanceHelpers.UsedWeight(pricesList.ResponseHeaders);
		Singleton.Instance.HandleRateLimits(weight.Value);

		pricesList = Client.Get24HPricesList();
	}

	var tickers = new Dictionary<string, BinanceStreamTick>();

	foreach (Binance24HPrice price in pricesList.Data)
	{
		tickers.Add(price.Symbol, new BinanceStreamTick
		{
			TotalTradedQuoteAssetVolume = price.TotalTradedQuoteAssetVolume,
			TotalTradedBaseAssetVolume = price.TotalTradedBaseAssetVolume,
			LowPrice = price.LowPrice,
			HighPrice = price.HighPrice,
			OpenPrice = price.OpenPrice,
			AskQuantity = price.AskQuantity,
			AskPrice = price.AskPrice,
			BidQuantity = price.BidQuantity,
			BidPrice = price.BidPrice,
			LastQuantity = price.LastQuantity,
			LastPrice = price.LastPrice,
			PrevDayClosePrice = price.PrevDayClosePrice,
			WeightedAveragePrice = price.WeightedAveragePrice,
			PriceChangePercent = price.PriceChangePercent,
			PriceChange = price.PriceChange,
			Symbol = price.Symbol
		});
	}

	Tickers = tickers;

	SocketClient.SubscribeToAllSymbolTickerUpdates(data =>
	{
		foreach (BinanceStreamTick tick in data)
			Tickers[tick.Symbol] = tick;
	});
}
```

**Comment by JKorf** [comment]
Seems to be a connection issue. The underlying socket connection is interrupted/disconnected and it automatically reconnects. 
`An existing connection was forcibly closed by the remote host..`

Is it a consistent problem with that specific stream? Always at the same time or random?

**Comment by Hulkstance** [comment]
It happens everytime, only with this particular stream.

**Comment by JKorf** [comment]
It runs fine for me, which makes it hard to figure out what the problem is. Can you try to run this code in a new Console application? It is the code you pasted with removed rate limits:
````C#
        private static BinanceClient Client;
        private static BinanceSocketClient SocketClient;
        private static Dictionary<string, BinanceStreamTick> Tickers;

        static async Task Main(string[] args)
        {
            Client = new BinanceClient();
            SocketClient = new BinanceSocketClient(new BinanceSocketClientOptions
            {
                LogVerbosity = LogVerbosity.Debug
            });
            GetTickers();

            Console.ReadLine();
        }

        public static void GetTickers()
        {
            var pricesList = Client.Get24HPricesList();
            var tickers = new Dictionary<string, BinanceStreamTick>();

            foreach (Binance24HPrice price in pricesList.Data)
            {
                tickers.Add(price.Symbol, new BinanceStreamTick
                {
                    TotalTradedQuoteAssetVolume = price.TotalTradedQuoteAssetVolume,
                    TotalTradedBaseAssetVolume = price.TotalTradedBaseAssetVolume,
                    LowPrice = price.LowPrice,
                    HighPrice = price.HighPrice,
                    OpenPrice = price.OpenPrice,
                    AskQuantity = price.AskQuantity,
                    AskPrice = price.AskPrice,
                    BidQuantity = price.BidQuantity,
                    BidPrice = price.BidPrice,
                    LastQuantity = price.LastQuantity,
                    LastPrice = price.LastPrice,
                    PrevDayClosePrice = price.PrevDayClosePrice,
                    WeightedAveragePrice = price.WeightedAveragePrice,
                    PriceChangePercent = price.PriceChangePercent,
                    PriceChange = price.PriceChange,
                    Symbol = price.Symbol
                });
            }

            Tickers = tickers;

            SocketClient.SubscribeToAllSymbolTickerUpdates(data =>
            {
                foreach (BinanceStreamTick tick in data)
                    Tickers[tick.Symbol] = tick;
            });
        }
````

**Comment by Hulkstance** [comment]
> 
> 
> It runs fine for me, which makes it hard to figure out what the problem is. Can you try to run this code in a new Console application? It is the code you pasted with removed rate limits:
> 
> ```cs
>         private static BinanceClient Client;
>         private static BinanceSocketClient SocketClient;
>         private static Dictionary<string, BinanceStreamTick> Tickers;
> 
>         static async Task Main(string[] args)
>         {
>             Client = new BinanceClient();
>             SocketClient = new BinanceSocketClient(new BinanceSocketClientOptions
>             {
>                 LogVerbosity = LogVerbosity.Debug
>             });
>             GetTickers();
> 
>             Console.ReadLine();
>         }
> 
>         public static void GetTickers()
>         {
>             var pricesList = Client.Get24HPricesList();
>             var tickers = new Dictionary<string, BinanceStreamTick>();
> 
>             foreach (Binance24HPrice price in pricesList.Data)
>             {
>                 tickers.Add(price.Symbol, new BinanceStreamTick
>                 {
>                     TotalTradedQuoteAssetVolume = price.TotalTradedQuoteAssetVolume,
>                     TotalTradedBaseAssetVolume = price.TotalTradedBaseAssetVolume,
>                     LowPrice = price.LowPrice,
>                     HighPrice = price.HighPrice,
>                     OpenPrice = price.OpenPrice,
>                     AskQuantity = price.AskQuantity,
>                     AskPrice = price.AskPrice,
>                     BidQuantity = price.BidQuantity,
>                     BidPrice = price.BidPrice,
>                     LastQuantity = price.LastQuantity,
>                     LastPrice = price.LastPrice,
>                     PrevDayClosePrice = price.PrevDayClosePrice,
>                     WeightedAveragePrice = price.WeightedAveragePrice,
>                     PriceChangePercent = price.PriceChangePercent,
>                     PriceChange = price.PriceChange,
>                     Symbol = price.Symbol
>                 });
>             }
> 
>             Tickers = tickers;
> 
>             SocketClient.SubscribeToAllSymbolTickerUpdates(data =>
>             {
>                 foreach (BinanceStreamTick tick in data)
>                     Tickers[tick.Symbol] = tick;
>             });
>         }
> ```

Same thing is happening again.

```
'Test.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Admin\Desktop\Test\Test\bin\Debug\netcoreapp3.1\Test.dll'. Symbols loaded.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'Test.Program.<Main>'
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Threading.Tasks.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'Test.Program.Main'
Step into: Stepping over non-user code 'Test.Program.<Main>d__3..ctor'
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Admin\Desktop\Test\Test\bin\Debug\netcoreapp3.1\Binance.Net.dll'. 
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Admin\Desktop\Test\Test\bin\Debug\netcoreapp3.1\CryptoExchange.Net.dll'. 
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Admin\Desktop\Test\Test\bin\Debug\netcoreapp3.1\Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Diagnostics.Debug.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Net.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Net.WebProxy.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Diagnostics.Tracing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Net.Security.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Security.Cryptography.X509Certificates.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Linq.Expressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2020/08/27 17:20:39:265 | Debug | Client configuration: LogVerbosity: Debug, Writers: 1, Credentials: -, BaseAddress: wss://stream.binance.com:9443/ws/, Proxy: -, AutoReconnect: True, ReconnectInterval: 00:00:05, SocketResponseTimeout: 00:00:10, SocketSubscriptionsCombineTarget: 
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Diagnostics.DiagnosticSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Threading.Timer.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Net.Sockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Threading.Overlapped.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Net.NameResolution.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Security.Cryptography.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Security.Principal.Windows.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Security.Claims.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Security.Principal.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Security.Cryptography.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Buffers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Runtime.Serialization.Formatters.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Diagnostics.TraceSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Runtime.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Runtime.Serialization.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Data.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Private.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.ComponentModel.TypeConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.ComponentModel.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Reflection.Emit.ILGeneration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Reflection.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Reflection.Emit.Lightweight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Collections.Specialized.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Drawing.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Admin\Desktop\Test\Test\bin\Debug\netcoreapp3.1\WebSocket4Net.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2020/08/27 17:20:41:045 | Debug | Created new socket for wss://stream.binance.com:9443/ws/!ticker@arr
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Admin\Desktop\Test\Test\bin\Debug\netcoreapp3.1\SuperSocket.ClientEngine.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2020/08/27 17:20:41:090 | Debug | Socket 1 connecting
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.IO.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Text.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Security.Cryptography.Algorithms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2020/08/27 17:20:42:495 | Debug | Socket 1 connected
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Text.Encoding.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2020/08/27 17:20:52:635 | Debug | Socket 1 received data: ...
2020/08/27 17:21:10:677 | Debug | Socket 1 received data: ...
2020/08/27 17:21:29:181 | Debug | Socket 1 received data: ...
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Resources.ResourceManager.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.IO.FileSystem.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Test.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2020/08/27 17:21:43:002 | Info | Socket 1 error: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.ReadAsync()
2020/08/27 17:21:43:004 | Info | Socket 1 Connection lost, will try to reconnect after 00:00:05
2020/08/27 17:21:48:033 | Debug | Socket 1 resetting
2020/08/27 17:21:48:035 | Debug | Socket 1 connecting
2020/08/27 17:21:50:583 | Debug | Socket 1 connected
2020/08/27 17:21:50:585 | Info | Socket 1 reconnected after 00:00:07.5813836
2020/08/27 17:21:50:588 | Debug | All subscription successfully resubscribed on reconnected socket.
2020/08/27 17:22:11:667 | Debug | Socket 1 received data: ...
```

**Comment by JKorf** [comment]
Is is possible for you to try it on a different machine?

**Comment by Hulkstance** [comment]
> 
> 
> Is is possible for you to try it on a different machine?

I just did and asked a friend to test it as well. It seems to be eduroam network causing it. Thanks and closing the issue.
