### ISSUE TITLE
OrderTypeConverter throws an exception during SubscribeToOrderUpdateStream callback data deserializing

### ISSUE THREAD

**Issue by sheretovev** [JKorf/Binance.Net#7]
System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.String'.
   at Binance.Net.Converters.OrderTypeConverter.<>c__DisplayClass5_0.<ReadJson>b__0(KeyValuePair`2 v)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Binance.Net.Converters.OrderTypeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Binance.Net.BinanceSocketClient.OnUserMessage(String data)
   at Binance.Net.BinanceSocketClient.<CreateUserStream>b__30_1(Object o, MessageReceivedEventArgs s)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.SslStreamTcpSession.<ReadAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by JKorf** [comment]
This should be resolved in the latest version

**Comment by blaataap** [comment]
Im having the same issue even though i updated to the most recent version: 2.3.1 The issue started after update to 2.3.1 and implementing the new subscribtetouserstream.

It seems to happen after placing an order and using the userstream so possibly on the socketClient.SubscribeToUserStream() -> orderInfoUpdate.

I have been able to reproduce this buy placing an order and subscribing to the user stream. As soon as i cancel the order from binance the error occurs.

**Comment by JKorf** [comment]
Hi, this should be fixed in the latest version again (2.3.3) currently being pushed to nuget. The bug reoccurred when I was cleaning some code (too rigorously).

**Comment by blaataap** [comment]
Aweseom work!

Just tested and confirmed that 2.3.3 fixed this issue.
