### ISSUE TITLE
Error while placing Stop Loss Order using Margin / SAPI

### ISSUE THREAD

**Issue by rockpinkfloyd14** [JKorf/Binance.Net#793]
Description: I am trying to place a stop loss market order on margin account using the endpoint binanceTrade.sapiPostMarginOrder().

Command that I ran:
t=binanceTrade.sapiPostMarginOrder({'symbol':'BTCUSDT','side':'SELL','type':'STOP_LOSS','timeInForce':'GTC','quantity':0.00035,'stopPrice':31000,'timestamp':binanceTrade.fetchTime()})

Expected This:
The stop loss order is supposed to trigger since the current market price is greater than 31000 and I have 0.00035 BTC in my account. But instead I get an unknown error:

Error Logs: 
>>>t=binanceTrade.sapiPostMarginOrder({'symbol':'BTCUSDT','side':'SELL','type':'STOP_LOSS','timeInForce':'GTC','quantity':0.00035,'stopPrice':31000,'timestamp':binance.fetchTime()})
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 593, in fetch
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://api.binance.com/sapi/v1/margin/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/binance.py", line 2975, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 609, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/binance.py", line 2969, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ccxt/base/exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeNotAvailable: binance {"code":-1000,"msg":"An unknown error occurred while processing the request."}

**Comment by JKorf** [comment]
Wrong library

**Comment by rockpinkfloyd14** [comment]
binanceTrade=binance

I am using still using Binance.
