### ISSUE TITLE
Problem with restoring the connections

### ISSUE THREAD

**Issue by karloballa** [JKorf/Binance.Net#948]
While I tried packages 7.x.y and 4.z.w a few times, this is the first time I used them for a longer time. In the meantime, I changed my sources significantly. The problem arises after connections are lost. Most of the time the connections are automatically restored, but it happens sometimes they don't. It is very hard to recreate errors since sometimes the program works for days and sometimes fails after one day. I'm using the Windows Forms framework with the latest packages. It seems that the newly changed program works well with old packages (6.13.4 and 3.9.0).

**Comment by JKorf** [comment]
Hm hard to say what's causing that. Do you have any logging of when it doesn't reconnect?

**Comment by karloballa** [comment]
No, unfortunately, but if you show me the debug pattern, I'll try again. 

At the moment I can only say that it works flawlessly with old packages.

**Comment by JKorf** [comment]
Logging can be enabled in the client options. Meanwhile version 8.x of Binance.Net and 5.x of CryptoExchange.Net have been released which provide some improvements to the reconnect stability. Let me know if you have any issues with the newer versions if you have time to update

**Comment by karloballa** [comment]
I have been using the new packages for almost 2 weeks without any problems. Thanks!

**Comment by JKorf** [comment]
Good to hear, thanks for the update!

**Comment by karloballa** [comment]
It was nice while it lasted :)

After about two weeks, prog disconnected and could not connect again.

I think the last packages that worked well for months were 13.4 and 3.9.0. Well, I wouldn't change the code, but after the computer lost power, the program couldn't reload the exchange data. I guess Binance changed something in the API, you sure know that much better.

Now back to the new packages. I don't think the problem has anything to do with trading, it's somewhere else. I'll turn on the debug and let prog do nothing to see what happens.

**Comment by karloballa** [comment]
I tried to create a trace log, but it seems that there is no log info about losing and reconnecting?! I switched on/off the internet but got nothing in the log. I don't have an idea how to debug the problem. 

We had a similar issue (https://github.com/JKorf/Binance.Net/issues/870), however, this time there is no problem with reconnecting after pausing program execution in the debugger, just random losing connection.

**Comment by JKorf** [comment]
There should be logs when disconnecting/reconnecting. When you switch off your internet it might take a little while for the socket to find out it's disconnected. If you leave it disconnected for up to a minute you should see logs. That's not an issue with the library btw, it's just how the tcp connection works.

**Comment by karloballa** [comment]
It seems I don't know how to log the socket stream. The connection was off between  23:44 and  23:49. This is the log from the Client:
2022-04-22 23:39:30.842 +02:00 [INF] Binance    | [2] Creating request for https://api.binance.com/api/v3/time
2022-04-22 23:39:32.145 +02:00 [DBG] Binance    | [2] Response received in 902ms
2022-04-22 23:39:32.311 +02:00 [INF] Binance    | [3] Creating request for https://api.binance.com/api/v3/time
2022-04-22 23:39:32.603 +02:00 [DBG] Binance    | [3] Response received in 290ms
2022-04-22 23:39:32.608 +02:00 [INF] Binance    | Spot Api Time offset within limits, set offset to 0ms
2022-04-22 23:39:32.718 +02:00 [INF] Binance    | [1] Creating request for https://api.binance.com/api/v3/account
2022-04-22 23:39:33.084 +02:00 [DBG] Binance    | [1] Response received in 274ms
2022-04-22 23:39:33.274 +02:00 [DBG] Binance    | Disposing client
2022-04-22 23:39:33.312 +02:00 [INF] Binance    | [4] Creating request for https://api.binance.com/api/v3/exchangeInfo
2022-04-22 23:39:36.493 +02:00 [DBG] Binance    | [4] Response received in 325ms
2022-04-22 23:39:38.847 +02:00 [INF] Binance    | Trade rules updated
2022-04-22 23:39:38.874 +02:00 [DBG] Binance    | Disposing client
2022-04-22 23:39:38.913 +02:00 [INF] Binance    | [5] Creating request for https://api.binance.com/api/v3/openOrders
2022-04-22 23:39:39.313 +02:00 [DBG] Binance    | [5] Response received in 396ms
2022-04-22 23:39:39.340 +02:00 [DBG] Binance    | Disposing client
2022-04-22 23:39:41.421 +02:00 [INF] Binance    | [8] Creating request for https://api.binance.com/api/v3/userDataStream
2022-04-22 23:39:41.810 +02:00 [DBG] Binance    | [8] Response received in 375ms
2022-04-22 23:39:43.286 +02:00 [DBG] Binance    | Disposing client
2022-04-22 23:41:30.502 +02:00 [INF] Binance    | [11] Creating request for https://api.binance.com/api/v3/userDataStream
2022-04-22 23:41:32.543 +02:00 [DBG] Binance    | [11] Response received in 2040ms
2022-04-22 23:41:32.547 +02:00 [DBG] Binance    | Disposing client
2022-04-22 23:43:43.688 +02:00 [INF] Binance    | [2] Creating request for https://api.binance.com/api/v3/time
2022-04-22 23:43:46.121 +02:00 [DBG] Binance    | [2] Response received in 1301ms
2022-04-22 23:43:46.316 +02:00 [INF] Binance    | [3] Creating request for https://api.binance.com/api/v3/time
2022-04-22 23:43:46.581 +02:00 [DBG] Binance    | [3] Response received in 264ms
2022-04-22 23:43:46.587 +02:00 [INF] Binance    | Spot Api Time offset within limits, set offset to 0ms
2022-04-22 23:43:46.757 +02:00 [INF] Binance    | [1] Creating request for https://api.binance.com/api/v3/account
2022-04-22 23:43:47.397 +02:00 [DBG] Binance    | [1] Response received in 262ms
2022-04-22 23:43:47.679 +02:00 [DBG] Binance    | Disposing client
2022-04-22 23:43:47.735 +02:00 [INF] Binance    | [4] Creating request for https://api.binance.com/api/v3/exchangeInfo
2022-04-22 23:43:52.447 +02:00 [DBG] Binance    | [4] Response received in 408ms
2022-04-22 23:43:57.265 +02:00 [INF] Binance    | Trade rules updated
2022-04-22 23:43:57.294 +02:00 [DBG] Binance    | Disposing client
2022-04-22 23:43:57.384 +02:00 [INF] Binance    | [5] Creating request for https://api.binance.com/api/v3/openOrders
2022-04-22 23:43:57.765 +02:00 [DBG] Binance    | [5] Response received in 379ms
2022-04-22 23:43:57.800 +02:00 [DBG] Binance    | Disposing client
2022-04-22 23:44:00.089 +02:00 [INF] Binance    | [8] Creating request for https://api.binance.com/api/v3/userDataStream
2022-04-22 23:44:00.496 +02:00 [DBG] Binance    | [8] Response received in 383ms
2022-04-22 23:44:02.357 +02:00 [DBG] Binance    | Disposing client
2022-04-22 23:49:08.275 +02:00 [INF] Binance    | [11] Creating request for https://api.binance.com/api/v3/userDataStream
2022-04-22 23:49:10.814 +02:00 [DBG] Binance    | [11] Response received in 2539ms
2022-04-22 23:49:10.819 +02:00 [DBG] Binance    | Disposing client
2022-04-23 00:00:33.448 +02:00 [INF] Binance    | [12] Creating request for https://api.binance.com/api/v3/userDataStream
2022-04-23 00:00:33.878 +02:00 [DBG] Binance    | [12] Response received in 428ms
2022-04-23 00:00:33.882 +02:00 [DBG] Binance    | Disposing client

**Comment by karloballa** [comment]
I deleted the previous comment since I found an error in initializing the socket log. Now, I will try to trace the bug, if there is one. I updated packages, so maybe everything will work now, I don't know :)

**Comment by karloballa** [comment]
Okay, 
setting up the socket log reveals what seems like a nasty bug. 
It is not exactly like the code below, but it boils down to it. 

socketClient_ = new BinanceSocketClient();  
...
...

BinanceClient.SetDefaultOptions(new BinanceClientOptions()
{
...
});

BinanceSocketClient.SetDefaultOptions(new BinanceSocketClientOptions()
{
...
});

Firstly I created the Socket, and then I initialize options. Wrong order! For the Client, it is no problem since I create the Client whenever I use it, but the Socket is permanent.

Now, it worked with some packages, but I suspect it could be the cause of not reconnecting the socket in some cases. We will see...

Thanks for the guidance!

**Comment by karloballa** [comment]
I know I'm boring, but it seems there is still some problem. Here is the log:

2022-04-23 16:04:11.739 +02:00 [DBG] Binance    | Socket 1 new socket created for wss://stream.binance.com:9443/stream
2022-04-23 16:04:11.782 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 16:04:13.116 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 16:04:13.165 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 16:04:13.577 +02:00 [INF] Binance    | Socket 1 subscription completed
2022-04-23 16:04:15.048 +02:00 [INF] Binance    | Socket 1 subscription completed
2022-04-23 16:13:19.903 +02:00 [DBG] Binance    | Socket 1 new socket created for wss://stream.binance.com:9443/stream
2022-04-23 16:13:19.931 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 16:13:21.426 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 16:13:21.473 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 16:13:21.888 +02:00 [INF] Binance    | Socket 1 subscription completed
2022-04-23 16:13:22.664 +02:00 [INF] Binance    | Socket 1 subscription completed
2022-04-23 16:14:37.756 +02:00 [DBG] Binance    | Socket 1 new socket created for wss://stream.binance.com:9443/stream
2022-04-23 16:14:37.777 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 16:14:39.235 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 16:14:39.270 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 16:14:39.662 +02:00 [INF] Binance    | Socket 1 subscription completed
2022-04-23 16:14:41.108 +02:00 [INF] Binance    | Socket 1 subscription completed
2022-04-23 20:35:14.217 +02:00 [WRN] Binance    | Socket 1 No data received for 00:00:10, reconnecting socket
2022-04-23 20:35:14.217 +02:00 [DBG] Binance    | Socket 1 closing
2022-04-23 20:35:14.279 +02:00 [DBG] Binance    | Socket 1 closed
2022-04-23 20:35:14.279 +02:00 [WRN] Binance    | Socket 1 Connection lost, will try to reconnect
2022-04-23 20:35:14.295 +02:00 [DBG] Binance    | Socket 1 resetting
2022-04-23 20:35:14.295 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 20:35:16.686 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 20:35:16.701 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 20:35:16.701 +02:00 [INF] Binance    | Socket 1 reconnected after 00:00:02.4218805
2022-04-23 20:35:17.264 +02:00 [DBG] Binance    | Socket 1 all subscription successfully resubscribed on reconnected socket.
2022-04-23 20:35:17.264 +02:00 [INF] Binance    | Socket 1 data connection restored.
2022-04-23 20:43:05.878 +02:00 [WRN] Binance    | Socket 1 No data received for 00:00:10, reconnecting socket
2022-04-23 20:43:05.878 +02:00 [DBG] Binance    | Socket 1 closing
2022-04-23 20:43:05.894 +02:00 [DBG] Binance    | Socket 1 closed
2022-04-23 20:43:05.894 +02:00 [WRN] Binance    | Socket 1 Connection lost, will try to reconnect
2022-04-23 20:43:05.894 +02:00 [DBG] Binance    | Socket 1 resetting
2022-04-23 20:43:05.894 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 20:43:13.332 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 20:43:13.347 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 20:43:13.378 +02:00 [INF] Binance    | Socket 1 reconnected after 00:00:07.4843948
2022-04-23 20:43:15.675 +02:00 [DBG] Binance    | Socket 1 all subscription successfully resubscribed on reconnected socket.
2022-04-23 20:43:15.675 +02:00 [INF] Binance    | Socket 1 data connection restored.
2022-04-23 20:43:25.847 +02:00 [WRN] Binance    | Socket 1 No data received for 00:00:10, reconnecting socket
2022-04-23 20:43:25.847 +02:00 [DBG] Binance    | Socket 1 closing
2022-04-23 20:43:25.847 +02:00 [DBG] Binance    | Socket 1 closed
2022-04-23 20:43:25.847 +02:00 [WRN] Binance    | Socket 1 Connection lost, will try to reconnect
2022-04-23 20:43:25.847 +02:00 [DBG] Binance    | Socket 1 resetting
2022-04-23 20:43:25.847 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 20:43:35.879 +02:00 [DBG] Binance    | Socket 1 connection failed: WebSocketException - Unable to connect to the remote server
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.<ConnectAsync>d__86.MoveNext()
  WebException - The request was aborted: The request was canceled.
     at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()

2022-04-23 20:43:35.879 +02:00 [DBG] Binance    | Socket 1 failed to reconnect, will try again in 00:00:05
2022-04-23 20:43:40.894 +02:00 [DBG] Binance    | Socket 1 resetting
2022-04-23 20:43:40.894 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 20:43:43.788 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 20:43:43.788 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 20:43:43.788 +02:00 [INF] Binance    | Socket 1 reconnected after 00:00:17.9410442
2022-04-23 20:43:53.818 +02:00 [DBG] Binance    | Socket 1 resubscribing all subscriptions failed on reconnected socket. Error: : No response on subscription request received . Disconnecting and reconnecting.
2022-04-23 20:43:53.818 +02:00 [DBG] Binance    | Socket 1 closing
2022-04-23 20:43:53.833 +02:00 [DBG] Binance    | Socket 1 closed
2022-04-23 20:43:53.833 +02:00 [DBG] Binance    | Socket 1 resetting
2022-04-23 20:43:53.833 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 20:43:56.677 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 20:43:56.740 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 20:43:56.740 +02:00 [INF] Binance    | Socket 1 reconnected after 00:00:30.8923354
2022-04-23 20:44:06.754 +02:00 [DBG] Binance    | Socket 1 resubscribing all subscriptions failed on reconnected socket. Error: : No response on subscription request received . Disconnecting and reconnecting.
2022-04-23 20:44:06.754 +02:00 [DBG] Binance    | Socket 1 closing
2022-04-23 20:44:06.754 +02:00 [DBG] Binance    | Socket 1 closed
2022-04-23 20:44:06.754 +02:00 [DBG] Binance    | Socket 1 resetting
2022-04-23 20:44:06.754 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 20:44:13.439 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 20:44:13.486 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 20:44:13.486 +02:00 [INF] Binance    | Socket 1 reconnected after 00:00:47.6383209
2022-04-23 20:44:14.376 +02:00 [DBG] Binance    | Socket 1 all subscription successfully resubscribed on reconnected socket.
2022-04-23 20:44:14.376 +02:00 [INF] Binance    | Socket 1 data connection restored.
2022-04-23 20:45:45.009 +02:00 [WRN] Binance    | Socket 1 No data received for 00:00:10, reconnecting socket
2022-04-23 20:45:45.009 +02:00 [DBG] Binance    | Socket 1 closing
2022-04-23 20:45:45.009 +02:00 [DBG] Binance    | Socket 1 closed
2022-04-23 20:45:45.009 +02:00 [WRN] Binance    | Socket 1 Connection lost, will try to reconnect
2022-04-23 20:45:45.025 +02:00 [DBG] Binance    | Socket 1 resetting
2022-04-23 20:45:45.025 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 20:45:50.119 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 20:45:50.119 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 20:45:50.119 +02:00 [INF] Binance    | Socket 1 reconnected after 00:00:05.1093866
2022-04-23 20:46:00.120 +02:00 [DBG] Binance    | Socket 1 resubscribing all subscriptions failed on reconnected socket. Error: : No response on subscription request received . Disconnecting and reconnecting.
2022-04-23 20:46:00.120 +02:00 [DBG] Binance    | Socket 1 closing
2022-04-23 20:46:00.136 +02:00 [DBG] Binance    | Socket 1 closed
2022-04-23 20:46:00.136 +02:00 [DBG] Binance    | Socket 1 resetting
2022-04-23 20:46:00.136 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 20:46:05.120 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 20:46:05.151 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 20:46:05.151 +02:00 [INF] Binance    | Socket 1 reconnected after 00:00:20.1418379
2022-04-23 20:46:15.151 +02:00 [DBG] Binance    | Socket 1 resubscribing all subscriptions failed on reconnected socket. Error: : No response on subscription request received . Disconnecting and reconnecting.
2022-04-23 20:46:15.151 +02:00 [DBG] Binance    | Socket 1 closing
2022-04-23 20:46:15.167 +02:00 [DBG] Binance    | Socket 1 closed
2022-04-23 20:46:15.167 +02:00 [DBG] Binance    | Socket 1 resetting
2022-04-23 20:46:15.167 +02:00 [DBG] Binance    | Socket 1 connecting
2022-04-23 20:46:18.011 +02:00 [DBG] Binance    | Socket 1 Starting task checking for no data received for 00:00:10
2022-04-23 20:46:18.011 +02:00 [DBG] Binance    | Socket 1 connected to wss://stream.binance.com:9443/stream
2022-04-23 20:46:18.011 +02:00 [INF] Binance    | Socket 1 reconnected after 00:00:33.0012366
2022-04-23 20:46:28.026 +02:00 [DBG] Binance    | Socket 1 resubscribing all subscriptions failed on reconnected socket. Error: : No response on subscription request received . Disconnecting and reconnecting.
2022-04-23 20:46:28.026 +02:00 [DBG] Binance    | Socket 1 closing

**Comment by karloballa** [comment]
I noticed that the problem with the socket connection occurs when the internet connection is shaky, so I tried to turn on and off the WiFi connection in Windows as quickly as possible. After several attempts, the socket is confused :/ 
It seems that I finally managed to recreate the issue.

**Comment by JKorf** [comment]
I've found a timing issue in the reconnection logic where it could sometimes cause the reconnect loop to stop without notification or anything if the connection is dropped during the resubscribing of the subscriptions. This should be resolved in the latest version, could you try this?

**Comment by karloballa** [comment]
Thx! 
I upgraded the packages. With my unstable net, bugs should show up quickly if there are any.

**Comment by karloballa** [comment]
I have a question about the log files. At some point, the log files become too large and it would be nice if I could delete them without stopping the program.

**Comment by karloballa** [comment]
Hello,

is it possible that the latest packages have a problem with restoring the connections? I upgraded packages from v5.1.8 and v8.0.12 and had the problem within a day. Maybe it's a coincidence.

**Comment by JKorf** [comment]
Hi, I'm not aware of any issues in the latest version. Though the latest version of Binance is 8.1.6, any reason you're on 8.0.12? 
It's possible that there was an issue in that version.
It would be quite the coincidence if it wasn't related to the update

**Comment by karloballa** [comment]
It seems that something is broken.

I do not update packages as long as they work. The last packages that worked well for me were v8.0.12 with v5.1.8. Since I had to restart the computer a few days ago, when I started the program I noticed that the GetExchangeInfoAsinc method was not working. Then I updated the packages. Since then the program have trouble reconnecting.

**Comment by JKorf** [comment]
I haven't seen any reports on issue with reconnecting with the latest version. What is the behavior? Do you have some logging?

**Comment by JKorf** [comment]
Thanks, that was really useful. The issue was in the `no data` timeout monitoring. When there was no data received for 30 seconds it closed the connection instead of reconnecting it. I've pushed CryptoExchange.Net version 5.2.3 in which it is fixed. You can manually install CryptoExchange.Net 5.2.3 for now in your project, the next Binance release will have the updated reference.

**Comment by karloballa** [comment]
Thanks for the quick update! ;)
